### PR TITLE
WIP Start using mypy for static type checking

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/thoth-station/common/pull/520

### CODE REVIEW

**Comment by fridex** [comment]
The error reported is actually correct:

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /tmp/src/github.com/thoth-station/analyzer
plugins: cov-2.8.1, mypy-0.4.1, timeout-1.3.3
collected 3 items

Running mypy on 3 files... done with status 1
Found 1 error in 1 file (checked 3 source files)

thoth/analyzer/__init__.py .                                             [ 33%]
thoth/analyzer/cli.py F                                                  [ 66%]
thoth/analyzer/command.py .                                              [100%]

=================================== FAILURES ===================================
____________________________ thoth/analyzer/cli.py _____________________________
37:1: error: Cannot find module named 'thoth.common'
37:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
========================= 1 failed, 2 passed in 1.76s ==========================

```

We don't have types shiped with thoth-common package. We need to release a new version with https://github.com/thoth-station/common/pull/520 to fix this issue.

**Comment by goern** [comment]
ping!?

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
> is this still valid?

Yes, we will need rebase this.

**Comment by fridex** [comment]
/close

... no longer relevant.

**Pull request closed without merging**
