### PR TITLE
preparing release 0.0.7

### PR DESCRIPTION
**Pull request by goern**
Starting with this release we have a Zuul-CI pipeline that:

* lints on Pull Requrest and gate/merge

### CODE REVIEW

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
@fridex please review using github and dont add the `approved` label or do a `/approve`

**Comment by fridex** [comment]
Looks good to me. (Except I don't like the style of breaking lines with
closing brackets :) ).

**Comment by goern** [comment]
like https://github.com/thoth-station/analyzer/pull/6/files#diff-c7bd1dfbe2b17aaccc3079e3db0d98c2R88 ? ja, most of the reformating is due to coala complaints... :/

could you github: review -> approve it, so we can test zuul pipeline too.

**Pull request merged**
